name: Display Weather

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:      # Allows manual triggering of the workflow

jobs:
  get-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get weather information
        env:
          API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          # Set the city and units (metric for Celsius, imperial for Fahrenheit)
          CITY="London"
          UNITS="metric" # use "imperial" for Fahrenheit

          # Call the weather API
          response=$(curl -s "https://api.openweathermap.org/data/2.5/weather?q=${CITY}&units=${UNITS}&appid=${API_KEY}")

          # Parse and display the weather information
          temp=$(echo $response | jq '.main.temp')
          weather=$(echo $response | jq -r '.weather[0].description')

          echo "The current temperature in ${CITY} is ${temp}° and the weather is ${weather}."
