name: WeatherAPI CI/CD

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every hour

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.8 # Replace with your desired Go version

      - name: Fetch Weather Data
        run: |
          # Replace "YOUR_API_KEY" and "YOUR_LOCATION" with your API key and location
          API_KEY=${{ secrets.WEATHER_API_KEY }}
          LOCATION="Hanoi"
          RESPONSE=$(curl -s "https://api.weatherapi.com/v1/current.json?q=$LOCATION&key=$API_KEY")
          echo "Weather Data: $RESPONSE"
      - name: Update README.md
        run: |
          # Get the weather data from the previous step's output
          WEATHER_DATA="${{ steps.fetch-weather.outputs.weatherData }}"
          
          # Update the README.md file with the weather information
          echo "## Weather Information" > README.md
          echo "```" >> README.md
          echo "$WEATHER_DATA" >> README.md
          echo "```" >> README.md
          
          # Commit the changes to the repository
          git config --global user.name "ametist2502"
          git config --global user.email "whaleblue2002@gmail.com"
          git add README.md
          git commit -m "Update weather information in README.md"
          git push origin main
